### ISSUE TITLE
Error: Dynamic require defined at line 5; not supported by Metro

### ISSUE THREAD

**Issue by kentdev92** [GoodDollar/gun-webcrypto-react-native#10]
### Description
The firstly I want say thank you so much to create this example about using gunjs on react native

### Steps to reproduce
I'm just clone this repo into my laptop and tried to run it. But it not work as my expect. its stuck at loading js and showing a description like this pic below here about: Error: Dynamic require defined at line 5; not supported by Metro.
Please help me to take a look and give me a solution to fix this. Thank you so much

![image](https://user-images.githubusercontent.com/17426288/132583168-38493168-7dc4-44e2-b3b2-c7c6598b7c69.png)

**Comment by sirpy** [comment]
@kentdev92 hey from a quick look, i see that the example is set to use gun from amark/gun#master
so something could have changed there.
This seems like an issue I had in the past, in sea.js it uses gun's custom "require" wrapper "USE".
first you can try using @gooddollar/gun as your gun version
otherwise to use the latest master you'd have to make a PR or fork, to replace usages of USE with require (just for external modules like buffer and text-encoding)

**Comment by kentdev92** [comment]
@sirpy thank you so much for your help!

**Comment by sirpy** [comment]
@kentdev92 did it solve the issue? if so please close the this
